# Generated by Django 3.2.8 on 2021-10-31 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_resume_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='file_path',
        ),
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
